services:
  db:
    image: postgres:16
    container_name: pastita_postgres
    environment:
      POSTGRES_USER: pastita
      POSTGRES_PASSWORD: pastita
      POSTGRES_DB: pastita
    ports:
      - "5432:5432"
    volumes:
      - ./_data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pastita -d pastita"]
      interval: 5s
      timeout: 3s
      retries: 10
